### ISSUE TITLE
itunes

### ISSUE THREAD

**Issue by KENPOKASMMA1982** [RealNigma/iTunesMusicSearch#1]
hello from Greece!!!please any demo web?I have no idea from programming and I dont know how to make it!!!I am begging youuuuuuuuuuu!!!

**Comment by RealNigma** [comment]
Hello! You can read about iTunes API here:
https://developer.apple.com/library/archive/documentation/AudioVideo/Conceptual/iTuneSearchAPI/Searching.html#//apple_ref/doc/uid/TP40017632-CH5-SW1

**Comment by KENPOKASMMA1982** [comment]
hellooooooooo....thanks but I have no idea from developing!!!please can you make one demo web link?
